table dim_date
	lineageTag: 7a9e0f6c-8f9b-44a7-8500-51d106097433

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: aa826972-07ed-4d9a-ae93-74da376bfaa3
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: 4367445b-ded7-4290-8cb0-9db4fc548336
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 3f03f26b-1cce-4c8f-bbfe-d697a42695fa
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: dc1d55a4-c91b-412c-b2d0-2deb4052d03f
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: 56af9aa6-be07-48dc-8168-9fde4c86e4cb
		summarizeBy: none
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 5683dde2-24f3-414e-9caf-a3bd5b76f005
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 71d63ac8-286e-42ff-ab7a-c882a8c831d8
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Datatatatta\data\processed\cleaned_date_dimension.csv"), [Delimiter = ",", Columns = 7, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"month", Int64.Type}, {"day", Int64.Type}, {"is_weekend", Int64.Type}, {"month_name", type text}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

