table 05_category_inflows
	lineageTag: e3709225-b645-4fe6-99a9-704b4e4b1938

	/// Net inflow by category
	measure 'Category Net Inflow (₹ Cr)' = SUM('05_category_inflows'[net_inflow_crore])
		formatString: ₹#,##0
		lineageTag: d4e1b612-954a-4597-b67b-e4415eb2042c

	/// Top 5 categories by net inflow FY25 (returns table for TopN visual use)
	measure 'Category Inflow Rank' = RANKX(ALLSELECTED('05_category_inflows'[category]), CALCULATE(SUM('05_category_inflows'[net_inflow_crore])), , DESC, Dense)
		formatString: #,##0
		lineageTag: fa27618b-b7fd-4d4c-a132-d3ada5b6b485

	column month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 606e43e3-3fe4-4094-acb1-1d193bea7915
		summarizeBy: none
		sourceColumn: month

		variation Variation
			isDefault
			relationship: 620728a2-90c1-43a3-8bcc-24cd8a548d1f
			defaultHierarchy: LocalDateTable_7b7a4566-9750-4447-996f-9bb70c76a338.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column category
		dataType: string
		lineageTag: c720d6b2-40f6-4b7e-920e-67320339fe6d
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column net_inflow_crore
		dataType: int64
		formatString: 0
		lineageTag: de47b0f4-db1e-4f8d-971f-9035fa94bc98
		summarizeBy: sum
		sourceColumn: net_inflow_crore

		annotation SummarizationSetBy = Automatic

	partition 05_category_inflows = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Datatatatta\data\processed\cleaned_category_inflows.csv"), [Delimiter = ",", Columns = 3, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"month", type date}, {"category", type text}, {"net_inflow_crore", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

