table Axis_Bluechip_nav
	lineageTag: 64bcb85e-e450-4402-b6f7-987f680f3272

	column date
		dataType: string
		lineageTag: 89e45479-291e-4c6c-9e28-738097ab6783
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column nav
		dataType: double
		lineageTag: d17ecb4b-e748-428b-b41b-49076dad5496
		summarizeBy: sum
		sourceColumn: nav

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Axis_Bluechip_nav = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Datatatatta\data\raw\Axis_Bluechip_nav.csv"), [Delimiter = ",", Columns = 2, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"date", type text}, {"nav", type number}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

