"""
Bluestock Mutual Fund Weekly Performance Email Digest Generator.
This script extracts weekly performance KPIs and transaction summary metrics
from the SQLite database, compiles them into a structured HTML email template,
and mocks an email delivery alert.
"""
import os
import sqlite3
import smtplib
import pandas as pd
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# Paths
workspace = r"c:\Datatatatta"
db_path = os.path.join(workspace, "data", "db", "bluestock_mf.db")

def generate_weekly_report():
    """
    Queries the SQLite relational database to extract performance KPIs and transaction summary metrics,
    and returns a formatted HTML weekly performance report.
    """
    conn = sqlite3.connect(db_path)
    
    # 1. Fetch Top 3 Performing Funds (3-Year return)
    top_funds = pd.read_sql_query("""
        SELECT f.scheme_name, f.fund_house, p.return_3yr_pct, p.morningstar_rating
        FROM fact_performance p
        JOIN dim_fund f ON p.amfi_code = f.amfi_code
        ORDER BY p.return_3yr_pct DESC
        LIMIT 3
    """, conn)
    
    # 2. Fetch Weekly Transaction Metrics
    tx_metrics = pd.read_sql_query("""
        SELECT COUNT(*) AS total_tx, ROUND(SUM(amount_inr), 2) AS total_vol
        FROM fact_transactions
    """, conn)
    
    conn.close()
    
    # 3. Create HTML Email Template
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333333; margin: 0; padding: 20px; }}
            .container {{ max-width: 600px; margin: 0 auto; background-color: #ffffff; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden; }}
            .header {{ background: linear-gradient(135deg, #1f77b4, #0f4c81); color: #ffffff; padding: 30px; text-align: center; }}
            .header h1 {{ margin: 0; font-size: 24px; }}
            .content {{ padding: 30px; }}
            .metric-box {{ display: flex; justify-content: space-around; margin-bottom: 30px; background-color: #f7f9fb; padding: 20px; border-radius: 6px; }}
            .metric {{ text-align: center; }}
            .metric-value {{ font-size: 22px; font-weight: bold; color: #1f77b4; }}
            .metric-label {{ font-size: 12px; color: #666666; text-transform: uppercase; margin-top: 5px; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
            th {{ background-color: #f2f2f2; text-align: left; padding: 10px; font-size: 13px; color: #555555; }}
            td {{ padding: 10px; border-bottom: 1px solid #e0e0e0; font-size: 14px; }}
            .footer {{ background-color: #f9f9f9; padding: 20px; text-align: center; font-size: 12px; color: #999999; border-top: 1px solid #e0e0e0; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>Bluestock MF Performance Digest</h1>
                <p style="margin: 5px 0 0 0; font-size: 14px; opacity: 0.9;">Your Weekly Mutual Fund Portfolio Report</p>
            </div>
            <div class="content">
                <h3>Weekly Investment Summary</h3>
                <div class="metric-box">
                    <div class="metric">
                        <div class="metric-value">{int(tx_metrics['total_tx'].iloc[0]):,}</div>
                        <div class="metric-label">Transactions</div>
                    </div>
                    <div class="metric">
                        <div class="metric-value">\u20b9{int(tx_metrics['total_vol'].iloc[0] / 10000000):,} Cr</div>
                        <div class="metric-label">Volume (Crores)</div>
                    </div>
                </div>
                
                <h3>Top 3 Performing Schemes</h3>
                <table>
                    <thead>
                        <tr>
                            <th>Scheme Name</th>
                            <th>Rating</th>
                            <th>3-Year Return</th>
                        </tr>
                    </thead>
                    <tbody>
    """
    
    for _, row in top_funds.iterrows():
        stars = "\u2605" * int(row['morningstar_rating'])
        html_content += f"""
                        <tr>
                            <td>{row['scheme_name']}</td>
                            <td style="color: #ffc107;">{stars}</td>
                            <td style="font-weight: bold; color: #2ca02c;">{row['return_3yr_pct']}%</td>
                        </tr>
        """
        
    html_content += """
                    </tbody>
                </table>
                <p style="margin-top: 30px; font-size: 13px; color: #666666; line-height: 1.5;">
                    This report has been automatically generated by your Bluestock MF ETL scheduler. For a full interactive analysis, please visit your local Streamlit dashboard app.
                </p>
            </div>
            <div class="footer">
                &copy; 2026 Bluestock Mutual Fund Analytics. All rights reserved.
            </div>
        </div>
    </body>
    </html>
    """
    
    return html_content

def send_email(html_body, to_email="recipient@example.com"):
    # Mock SMTP setup details (can be configured by user in their local env)
    from_email = "alerts@bluestockmf.com"
    
    msg = MIMEMultipart('alternative')
    msg['Subject'] = "Weekly Bluestock MF Performance Digest"
    msg['From'] = from_email
    msg['To'] = to_email
    
    msg.attach(MIMEText(html_body, 'html'))
    print("Email HTML report generated successfully!")
    print("Mock Sending email to:", to_email)
    # To enable live sending, uncomment below:
    # with smtplib.SMTP('smtp.gmail.com', 587) as server:
    #     server.starttls()
    #     server.login(from_email, "your_password")
    #     server.sendmail(from_email, to_email, msg.as_string())

if __name__ == "__main__":
    html = generate_weekly_report()
    send_email(html)
